name: notas_share
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # files and storage management
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # permissions
  permission_handler: ^11.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
